/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex6;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author plane
 */
public class FuncFrame extends javax.swing.JFrame {
    
    private CubicFunc f;

    /**
     * Creates new form SetupFrame
     */
    public FuncFrame() {
        initComponents();

        try{
            String lafClassName = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(lafClassName);
            SwingUtilities.updateComponentTreeUI(this);
        }catch(Exception ex){
          System.out.println("Error L&F Setting");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AField = new javax.swing.JTextField();
        BField = new javax.swing.JTextField();
        CField = new javax.swing.JTextField();
        DField = new javax.swing.JTextField();
        FuncCreate = new javax.swing.JButton();
        FunctionView = new javax.swing.JTextField();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        Direction = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ValueInField = new javax.swing.JTextField();
        ValueInButton = new javax.swing.JButton();
        ValueInResult = new javax.swing.JLabel();
        DifValueInField = new javax.swing.JTextField();
        DifValueInButton = new javax.swing.JButton();
        DifValueInResult = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MIN = new javax.swing.JLabel();
        MAX = new javax.swing.JLabel();
        DIV = new javax.swing.JLabel();
        IntegralMin = new javax.swing.JTextField();
        IntegralMax = new javax.swing.JTextField();
        IntegralDiv = new javax.swing.JTextField();
        IntegralButton = new javax.swing.JButton();
        IntegralResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AField.setText("0.0");
        AField.setInputVerifier(new IntegerInputVerifier());
        AField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFieldActionPerformed(evt);
            }
        });

        BField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BField.setText("0.0");
        BField.setInputVerifier(new IntegerInputVerifier());
        BField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFieldActionPerformed(evt);
            }
        });

        CField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CField.setText("0.0");
        CField.setInputVerifier(new IntegerInputVerifier());
        CField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFieldActionPerformed(evt);
            }
        });

        DField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DField.setText("0.0");
        DField.setInputVerifier(new IntegerInputVerifier());
        DField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFieldActionPerformed(evt);
            }
        });

        FuncCreate.setText("関数生成");
        FuncCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncCreateActionPerformed(evt);
            }
        });

        FunctionView.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        FunctionView.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FunctionView.setEnabled(false);

        A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A.setText("A");

        B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B.setText("B");

        C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.setText("C");

        D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D.setText("D");

        Direction.setBackground(new java.awt.Color(0, 228, 255));
        Direction.setFont(new java.awt.Font("MS UI Gothic", 0, 20)); // NOI18N
        Direction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Direction.setText("A x^3  +  B x^2  +  C x  +  D  =  y");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel5.setText("生成した関数");

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel6.setText("関数の操作");

        ValueInField.setText("　");
        ValueInField.setEnabled(false);
        ValueInField.setInputVerifier(new IntegerInputVerifier());
        ValueInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueInFieldActionPerformed(evt);
            }
        });

        ValueInButton.setText("y を計算");
        ValueInButton.setEnabled(false);
        ValueInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueInButtonActionPerformed(evt);
            }
        });

        ValueInResult.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        ValueInResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ValueInResult.setText("0.0");

        DifValueInField.setText("　");
        DifValueInField.setEnabled(false);
        DifValueInField.setInputVerifier(new IntegerInputVerifier());
        DifValueInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifValueInFieldActionPerformed(evt);
            }
        });

        DifValueInButton.setText("y' を計算");
        DifValueInButton.setEnabled(false);
        DifValueInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DifValueInButtonActionPerformed(evt);
            }
        });

        DifValueInResult.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        DifValueInResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DifValueInResult.setText("0.0");

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("範囲を指定して積分");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        MIN.setText("最小");

        MAX.setText("最大");

        DIV.setText("計算間隔");

        IntegralMin.setEnabled(false);
        IntegralMin.setInputVerifier(new IntegerInputVerifier());
        IntegralMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegralMinActionPerformed(evt);
            }
        });

        IntegralMax.setEnabled(false);
        IntegralMax.setInputVerifier(new IntegerInputVerifier());

        IntegralDiv.setEnabled(false);
        IntegralDiv.setInputVerifier(new IntegerInputVerifier());

        IntegralButton.setText("積分");
        IntegralButton.setEnabled(false);
        IntegralButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegralButtonActionPerformed(evt);
            }
        });

        IntegralResult.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        IntegralResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntegralResult.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Direction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FuncCreate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValueInField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValueInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValueInResult, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DifValueInField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DifValueInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DifValueInResult, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(MIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MAX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(136, 136, 136)))
                            .addComponent(FunctionView, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IntegralMin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IntegralMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IntegralDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IntegralButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IntegralResult, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Direction, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A)
                    .addComponent(B)
                    .addComponent(C)
                    .addComponent(D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FuncCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FunctionView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValueInField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValueInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValueInResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DifValueInField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DifValueInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DifValueInResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MIN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntegralMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegralMax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegralDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegralButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntegralResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFieldActionPerformed

    private void BFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BFieldActionPerformed

    private void CFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CFieldActionPerformed

    private void DFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DFieldActionPerformed

    private void FuncCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncCreateActionPerformed
        // TODO add your handling code here:
        this.f = new CubicFunc(this.convert(this.AField.getText()), this.convert(this.BField.getText()), this.convert(this.CField.getText()), this.convert(this.DField.getText()));
        this.ValueInResult.setText("0");
        this.DifValueInResult.setText("0");
        this.IntegralResult.setText("0");
        this.ConsoleUnlock();
    }//GEN-LAST:event_FuncCreateActionPerformed

    private void ValueInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueInFieldActionPerformed

    private void ValueInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueInButtonActionPerformed
        // TODO add your handling code here:
        double val = 0;
        try{
            val = this.convert(this.ValueInField.getText());
            this.ValueInResult.setText(String.valueOf(this.f.function(val)));
        }catch(Exception E){
            System.out.println("Value Error.");
        }
    }//GEN-LAST:event_ValueInButtonActionPerformed

    private void DifValueInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifValueInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DifValueInFieldActionPerformed

    private void DifValueInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DifValueInButtonActionPerformed
        // TODO add your handling code here:
        this.DifValueInResult.setText(String.valueOf(this.f.dfunction(this.convert(this.DifValueInField.getText()))));
    }//GEN-LAST:event_DifValueInButtonActionPerformed

    private void IntegralMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegralMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntegralMinActionPerformed

    private void IntegralButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegralButtonActionPerformed
        // TODO add your handling code here:
        double min = this.convert(this.IntegralMin.getText());
        double max = this.convert(this.IntegralMax.getText());
        int div = Integer.parseInt(this.IntegralMax.getText());
        this.IntegralResult.setText(String.valueOf(this.f.Integrate1(min, max, div)));
    }//GEN-LAST:event_IntegralButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncFrame().setVisible(true);
            }
        });
    }
    
    private double convert(String str){
        return Double.parseDouble(str);
    }
    
    private void ConsoleUnlock(){
        this.FunctionView.setText(this.f.getFunction());
        
        this.ValueInField.setEnabled(true);
        this.ValueInButton.setEnabled(true);
        this.DifValueInField.setEnabled(true);
        this.DifValueInButton.setEnabled(true);
        
        this.IntegralMin.setEnabled(true);
        this.IntegralMax.setEnabled(true);
        this.IntegralDiv.setEnabled(true);
        this.IntegralButton.setEnabled(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JTextField AField;
    private javax.swing.JLabel B;
    private javax.swing.JTextField BField;
    private javax.swing.JLabel C;
    private javax.swing.JTextField CField;
    private javax.swing.JLabel D;
    private javax.swing.JTextField DField;
    private javax.swing.JLabel DIV;
    private javax.swing.JButton DifValueInButton;
    private javax.swing.JTextField DifValueInField;
    private javax.swing.JLabel DifValueInResult;
    private javax.swing.JLabel Direction;
    private javax.swing.JButton FuncCreate;
    private javax.swing.JTextField FunctionView;
    private javax.swing.JButton IntegralButton;
    private javax.swing.JTextField IntegralDiv;
    private javax.swing.JTextField IntegralMax;
    private javax.swing.JTextField IntegralMin;
    private javax.swing.JLabel IntegralResult;
    private javax.swing.JLabel MAX;
    private javax.swing.JLabel MIN;
    private javax.swing.JButton ValueInButton;
    private javax.swing.JTextField ValueInField;
    private javax.swing.JLabel ValueInResult;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
