/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex6;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author plane
 */
public class IntegralFrame extends javax.swing.JFrame {

    /**
     * Creates new form IntegralFrame
     */
    
    Integral intg = new Integral();
    IntegralSimpson intgS = new IntegralSimpson();
    
    public IntegralFrame() {
        initComponents();

        try{
            String lafClassName = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(lafClassName);
            SwingUtilities.updateComponentTreeUI(this);
        }catch(Exception ex){
          System.out.println("Error L&F Setting");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        IntgArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        IntgSArea = new javax.swing.JTextArea();
        ValueField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CalcButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        gS = new javax.swing.JLabel();
        AutoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FILEOutput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntgArea.setColumns(20);
        IntgArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        IntgArea.setRows(5);
        jScrollPane1.setViewportView(IntgArea);

        IntgSArea.setColumns(20);
        IntgSArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        IntgSArea.setRows(5);
        jScrollPane2.setViewportView(IntgSArea);

        ValueField.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        ValueField.setText("0");
        ValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("分割数");

        CalcButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        CalcButton.setText("計算開始");
        CalcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("誤差");

        g.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        g.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        g.setText("0");

        gS.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        gS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gS.setText("0");

        AutoButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        AutoButton.setText("自動生成");
        AutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("台形公式");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("シンプソンの公式");

        FILEOutput.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        FILEOutput.setText("ファイル出力");
        FILEOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILEOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ValueField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AutoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CalcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FILEOutput)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ValueField)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CalcButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AutoButton)
                        .addComponent(FILEOutput)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gS, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueFieldActionPerformed

    private void CalcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcButtonActionPerformed
        // TODO add your handling code here:
//        入力された分割数で計算し表示
        int count = this.convert(this.ValueField.getText());
        this.calc(count);
        
    }//GEN-LAST:event_CalcButtonActionPerformed

    private void AutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoButtonActionPerformed
        // TODO add your handling code here:
//        自動で500ごとに値を出力
        for(int i = 1; i <= 10000; i+= 500){
            this.calc(i-1);
        }
    }//GEN-LAST:event_AutoButtonActionPerformed

    private void FILEOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILEOutputActionPerformed
        // TODO add your handling code here:
        this.outFile();
    }//GEN-LAST:event_FILEOutputActionPerformed
    
    private int convert(String str){
        return Integer.parseInt(str);
    }
    
    private void calc(int count){
//      台形公式とシンプソンによる計算
        double value1 = this.intg.setDiv(count) * 4.0;
        double x1 = (Math.PI - value1)/Math.PI * 100;
        double value2 = this.intgS.setDiv(count) * 4.0;
        double x2 = (Math.PI - value2)/Math.PI * 100;
//      値をGUIに表示
        String cstr = String.valueOf(count);
        this.IntgArea.append("分割数" + cstr + " : \t" + String.valueOf(value1) + "\n\t" + String.valueOf(x1) + "%" +"\n\n");
        this.IntgSArea.append("分割数" + cstr + " : \t"  + String.valueOf(value2) + "\n誤差率\t" + String.valueOf(x2) + "%" +"\n\n");
        this.g.setText(String.valueOf(x1) + "%");
        this.gS.setText(String.valueOf(x2) + "%");
    }
    
//    ファイル出力用関数
    private void outFile(){
        try {
            FileWriter fw = new FileWriter("result.csv", false);
            PrintWriter pw = new PrintWriter(new BufferedWriter(fw));
            for(int i = 1; i < 1000; i+=1){
        
                double value1 = this.intg.setDiv(i) * 4.0;
                double x1 = Math.abs((Math.PI - value1)/Math.PI * 100);
                double value2 = this.intgS.setDiv(i) * 4.0;
                double x2 = Math.abs((Math.PI - value2)/Math.PI * 100);
            
                pw.print(String.valueOf(i) + ",");
                pw.print(String.valueOf(value1) + ",");
                pw.print(String.valueOf(value2) + ",");
                pw.print(String.valueOf(x1) + ",");
                pw.println(String.valueOf(x2));
            }
            pw.close();
            fw.close();
//            ダイアログの表示
            JOptionPane.showMessageDialog(this, "ファイル出力完了しました。", "ファイル出力ダイアログ", JOptionPane.INFORMATION_MESSAGE );
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ファイル出力時にエラーが発生しました", "ファイル出力ダイアログ", JOptionPane.ERROR_MESSAGE );
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntegralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntegralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntegralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntegralFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntegralFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoButton;
    private javax.swing.JButton CalcButton;
    private javax.swing.JButton FILEOutput;
    private javax.swing.JTextArea IntgArea;
    private javax.swing.JTextArea IntgSArea;
    private javax.swing.JTextField ValueField;
    private javax.swing.JLabel g;
    private javax.swing.JLabel gS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
